apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: coolstore-pipeline
spec:
  params:
    - name: GIT_REPO
      type: string
      default: "https://github.com/dbrugger946/kai-coolstore.git"
    - name: BRANCH
      type: string
      default: "quarkus"
  workspaces:
    - name: app-build
    - name: maven-settings

  tasks:
    - name: fetch-repository
      taskRef:
        resolver: cluster 
        params:
          - name: kind
            value: task 
          - name: name
            value: git-clone 
          - name: namespace
            value: openshift-pipelines
      params: 
        - name: URL
          value: $(params.GIT_REPO)
        - name: REVISION 
          value: $(params.BRANCH)
        - name: DELETE_EXISTING 
          value: "true" 
      workspaces: 
        - name: output 
          workspace: app-build
    - name: maven-build
      taskRef:
        name: maven
        kind: Task 
      params:
        - name: MAVEN_IMAGE
          value: 'registry.access.redhat.com/ubi9/openjdk-21:1.20'
        - name: GOALS
          value:
            - '-B'
            - '-v'
            - clean
            - package
            - '-DskipTests'
            - '-Dmaven.wagon.http.ssl.insecure=true'
            - '--no-transfer-progress'
      workspaces:
        - name: source
          workspace: app-build
        - name: maven_settings
          workspace: maven-settings
      runAfter:
        - fetch-repository
    - name: buildah-build-push
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name 
            value: buildah 
          - name: namespace 
            value: openshift-pipelines 
      params:
        - name: DOCKERFILE
          value: 'src/main/docker/Dockerfile.jvm'
        - name: IMAGE 
          value: 'quay.io/dbrugger946/quarkus-coolstore:cicd.0.5'
      workspaces: 
        - name: source
          workspace: app-build
      runAfter:
        - maven-build 